apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: pwa-web-multi-backend-config
  namespace: designhub
spec:
  cdn:
    enabled: false
  connectionDraining:
    drainingTimeoutSec: 600
  healthCheck:
    checkIntervalSec: 10
    healthyThreshold: 2
    port: 8089
    requestPath: /manifest.json
    timeoutSec: 4
    unhealthyThreshold: 5
  timeoutSec: 600