apiVersion: v1
kind: Service
metadata:
  name: pwa
  namespace: designhub
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"pwa-web-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    svc: pwa-prod-central-web-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP
  selector:
    app: pwa-web-prod-central
